name: wei_inventoryv2
description: Application using inventory

publish_to: 'none'
version: 2.0.0

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: 1.0.4 # This is the package that we are using to manage the state of the app
  riverpod: 1.0.3
  dio: 4.0.6

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  multiple_result: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
flutter:

  uses-material-design: true
